package com.gymmate.shared.constants;

public enum AuditEventType {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  PASSWORD_CHANGE,
  PASSWORD_RESET_REQUEST,
  PASSWORD_RESET_SUCCESS,
  ACCOUNT_LOCKED,
  ACCOUNT_UNLOCKED,
  MFA_ENABLED,
  MFA_DISABLED,
  TOKEN_REFRESH,
  SUSPICIOUS_ACTIVITY,
  DATA_ACCESS,
  PERMISSION_DENIED,
  RATE_LIMIT_EXCEEDED
}
