-- Create new tables with UUID columns
CREATE TABLE users_new (
    id UUID PRIMARY KEY GENERATED BY DEFAULT AS RANDOM_UUID(),
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('MEMBER', 'STAFF', 'GYM_OWNER', 'ADMIN')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    gym_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

CREATE TABLE gyms_new (
    id UUID PRIMARY KEY GENERATED BY DEFAULT AS RANDOM_UUID(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    owner_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Copy data from old tables to new ones
INSERT INTO users_new (
    email, first_name, last_name, password_hash, phone_number,
    role, status, created_at, updated_at, last_login
)
SELECT
    email, first_name, last_name, password_hash, phone_number,
    role, status, created_at, updated_at, last_login
FROM users;

-- Drop old tables and rename new ones
DROP TABLE IF EXISTS gyms;
DROP TABLE IF EXISTS users;
ALTER TABLE users_new RENAME TO users;
ALTER TABLE gyms_new RENAME TO gyms;

-- Create indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_gym_id ON users(gym_id);

CREATE INDEX idx_gyms_owner_id ON gyms(owner_id);
CREATE INDEX idx_gyms_status ON gyms(status);
CREATE INDEX idx_gyms_city ON gyms(city);
